### PR TITLE
Add ipurl parameter

### PR DESCRIPTION
**Pull request by module0x90**
Make the URL what's used to find out your own public IP
configurable as a parameter, defaulting to http://ipecho.net/plain

### CODE REVIEW

**Comment by cedlemo** [comment]
I would like to merge it but before 
*    could we set a more meaning full name like url_for_ext_ip or something like that (this is not mandatory)
*   add documentation for this (when you add a property, a setter for this propery is automatically added)
Looks at line 22-92 int the net.lua file, it is relatively simple.

**Comment by module0x90** [comment]
cedlemo,

will do as suggested. Consider receiving another PR in the evening.
Cheers

Thomas

--
www​.​preissler​.​co​.​uk | Twitter: @module0x90

December 22 2015 2:18 PM, "cedlemo"  wrote:
	I would like to merge it but before
	* could we set a more meaning full name like url_for_ext_ip or something like that (this is not mandatory)
	* add documentation for this (when you add a property, a setter for this propery is automatically added) Looks at line 22-92 int the net.lua file, it is relatively simple.

**Comment by module0x90** [comment]
Here are the changes as required.


Cheers

**Comment by cedlemo** [comment]
Thanks !

**Pull request merged**
